name: Security Audit

on:
  push:
    branches: [ "main" ]
  schedule:
    - cron: '0 0 * * 0' # Dom, 00:00

jobs:
  audit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Rust Cache
      uses: Swatinem/rust-cache@v2

    - name: Install cargo-audit
      run: cargo install cargo-audit
      
    - name: Run cargo-audit (Vulnerability Tracker)
      run: cargo audit
